# Script para generar variables intermedias - EDU

# 1. Censos 

if (tipo == "censos") {
  data_edu <- data_filt %>% 
    mutate(age_25_mas = ifelse(edad_ci>=25, 1, 0),
           age_prim_c = case_when((pais_c=="COL"|pais_c=="BRA") & (edad_ci>=6&edad_ci<=10) ~ 1,
                                  (pais_c=="COL"|pais_c=="BRA") ~ 0,
                                  (pais_c=="BRB") & (edad_ci>=5&edad_ci<=10) ~ 1,
                                  (pais_c=="BRB") ~ 0,
                                  (pais_c=="TTO") & (edad_ci>=6&edad_ci<=12) ~ 1,
                                  (pais_c=="TTO") ~ 0,
                                  (edad_ci>=6&edad_ci<=10) ~ 1,
                                  (edad_ci<6&edad_ci>10) ~ 0,
                                  TRUE ~ NA),
           age_prim_sobre = case_when((pais_c=="BRB") &(asiste_ci==1 & aedu_ci==0 & edad_ci>=7)~ 1,
                                      (pais_c=="BRB") &(asiste_ci==1 & aedu_ci==1 & edad_ci>=8)~ 1,
                                      (pais_c=="BRB") &(asiste_ci==1 & aedu_ci==2 & edad_ci>=9)~ 1,
                                      (pais_c=="BRB") &(asiste_ci==1 & aedu_ci==3 & edad_ci>=10)~ 1,
                                      (pais_c=="BRB") &(asiste_ci==1 & aedu_ci==4 & edad_ci>=11)~ 1,
                                      (pais_c=="BRB") &(asiste_ci==1 & aedu_ci==5 & edad_ci>=12)~ 1,
                                      (pais_c=="BRB") &edad_ci>=5~ 0,
                                      (pais_c=="BRB")~ NA,
                                      (pais_c=="COL"|pais_c=="BRA") & (asiste_ci==1 & aedu_ci==0 & edad_ci>=8 & asispre_ci!= 1)~ 1,
                                      (pais_c=="COL"|pais_c=="BRA") & !(asiste_ci==1 & aedu_ci==0 & edad_ci>=8 & asispre_ci!= 1)~ 0,
                                      (pais_c=="COL"|pais_c=="BRA") & (asiste_ci==1 & aedu_ci==1 & edad_ci>=9)~ 1,
                                      (pais_c=="COL"|pais_c=="BRA") & (asiste_ci==1 & aedu_ci==2 & edad_ci>=10)~ 1,
                                      (pais_c=="COL"|pais_c=="BRA") & (asiste_ci==1 & aedu_ci==3 & edad_ci>=11)~ 1,
                                      (pais_c=="COL"|pais_c=="BRA") & (asiste_ci==1 & aedu_ci==4 & edad_ci>=12)~ 1,
                                      (pais_c=="TTO") & (asiste_ci==1 & aedu_ci==0 & edad_ci>=8)~ 1,
                                      (pais_c=="TTO") & !(asiste_ci==1 & aedu_ci==0 & edad_ci>=8)~ 0,
                                      (pais_c=="TTO") & (asiste_ci==1 & aedu_ci==1 & edad_ci>=9)~ 1,
                                      (pais_c=="TTO") & (asiste_ci==1 & aedu_ci==2 & edad_ci>=10)~ 1,
                                      (pais_c=="TTO") & (asiste_ci==1 & aedu_ci==3 & edad_ci>=11)~ 1,
                                      (pais_c=="TTO") & (asiste_ci==1 & aedu_ci==4 & edad_ci>=12)~ 1,                                 
                                      (pais_c=="TTO") & (asiste_ci==1 & aedu_ci==5 & edad_ci>=13)~ 1,
                                      (pais_c=="TTO") & (asiste_ci==1 & aedu_ci==6 & edad_ci>=14)~ 1,
                                      (pais_c=="TTO") & edad_ci<6 | is.na(aedu_ci)~ NA,
                                      (asiste_ci==1 & aedu_ci==0 & edad_ci>=8 & asispre_ci!= 1)~ 1,
                                      !(asiste_ci==1 & aedu_ci==0 & edad_ci>=8 & asispre_ci!= 1)~ 0,
                                      (asiste_ci==1 & aedu_ci==1 & edad_ci>=9)~ 1,
                                      (asiste_ci==1 & aedu_ci==2 & edad_ci>=10)~ 1,
                                      (asiste_ci==1 & aedu_ci==3 & edad_ci>=11)~ 1,
                                      (asiste_ci==1 & aedu_ci==4 & edad_ci>=12)~ 1,
                                      (asiste_ci==1 & aedu_ci==5 & edad_ci>=13)~ 1,
                                      edad_ci<6 | is.na(aedu_ci)~ NA,
                                      TRUE ~ NA),
           age_seco_c = case_when((pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN") & (edad_ci>=12&edad_ci<=16) ~ 1,
                                  (pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN") & !(edad_ci>=12&edad_ci<=16) ~ 0,
                                  (pais_c=="HTI"|pais_c=="SUR") & (edad_ci>=12&edad_ci<=18) ~ 1,
                                  (pais_c=="HTI"|pais_c=="SUR")& !(edad_ci>=12&edad_ci<=18) ~ 0,
                                  (pais_c=="BRB") & (edad_ci>=11&edad_ci<=15) ~ 1,
                                  (pais_c=="BRB")& !(edad_ci>=11&edad_ci<=15) ~ 0,
                                  (pais_c=="COL") & (edad_ci>=11&edad_ci<=16) ~ 1,
                                  (pais_c=="COL") & !(edad_ci>=11&edad_ci<=16) ~ 0,
                                  (pais_c=="BRA") & (edad_ci>=11&edad_ci<=17) ~ 1,
                                  (pais_c=="BRA")& !(edad_ci>=11&edad_ci<=17) ~ 0,                              
                                  (pais_c=="TTO") & (edad_ci>=13&edad_ci<=18) ~ 1,
                                  (pais_c=="TTO") & !(edad_ci>=13&edad_ci<=18) ~ 0,                                
                                  (edad_ci<12&edad_ci>17) ~ 1,
                                  !(edad_ci<12&edad_ci>17) ~ 0,
                                  TRUE ~ NA),
           age_term_s_c = case_when((pais_c=="COL"|pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN")&(edad_ci>=19&edad_ci<=21)~ 1,
                                    (pais_c=="COL"|pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN")&!(edad_ci>=19&edad_ci<=21)~ 0,
                                    (pais_c=="HTI"|pais_c=="SUR"|pais_c=="TTO")&(edad_ci>=21&edad_ci<=23) ~ 1,
                                    (pais_c=="HTI"|pais_c=="SUR"|pais_c=="TTO") &!(edad_ci>=21&edad_ci<=23) ~ 0,
                                    (pais_c=="BRB") &(edad_ci>=20&edad_ci<=22)~ 1,
                                    (pais_c=="BRB") & !(edad_ci>=20&edad_ci<=22) ~ 0,                                  
                                    (edad_ci>=20&edad_ci<=22)~ 1,
                                    !(edad_ci>=20&edad_ci<=22)~ 0,
                                    TRUE ~NA),
           age_tert_c = case_when((pais_c=="COL"|pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN") & (edad_ci>=17&edad_ci<=23) ~ 1,
                                  (pais_c=="COL"|pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN") & !(edad_ci>=17&edad_ci<=23) ~ 0,
                                  (pais_c=="HTI"|pais_c=="SUR"|pais_c=="TTO")&(edad_ci>=19&edad_ci<=23) ~ 1,
                                  (pais_c=="HTI"|pais_c=="SUR"|pais_c=="TTO")&!(edad_ci>=19&edad_ci<=23) ~ 0,
                                  (pais_c=="BRB") &(edad_ci>=16&edad_ci<=23)~ 1,
                                  (pais_c=="BRB") &!(edad_ci>=16&edad_ci<=23)~ 0,
                                  (edad_ci>=18&edad_ci<=23)~ 1,
                                  !(edad_ci>=18&edad_ci<=23)~ 0,
                                  TRUE ~NA),
           tprimaria = ifelse((edupc_ci ==1 | edusi_ci==1 | edusc_ci==1 | eduui_ci==1 | eduuc_ci==1),1,0),
           tsecundaria  = ifelse((edusc_ci ==1 | eduui_ci==1 | eduuc_ci==1),1,0),
           no_tsecundaria  = ifelse((edusc_ci  ==0 | eduui==0 | eduuc==0),1,0),
           tsecundaria_baja = ifelse((edus1c_ci ==1 | edusc_ci  ==1 | eduui==1 | eduuc==1),1,0),
           t_cond_primaria   = ifelse((tprimaria==1   & age_term_p_c==1),1,0),
           t_cond_secundaria = ifelse((tsecundaria==1 & age_term_s_c==1),1,0),
           age_edu = case_when(edad_ci>=4 & edad_ci<=5 ~ "preescolar",
                               edad_ci>=6 & edad_ci<=11 ~ "primaria", 
                               edad_ci>= 12 & edad_ci<=17 ~ "secundaria", 
                               edad_ci>= 18 ~ "terciaria",
                               edad_ci>=18 & edad_ci <=20 ~ "terciaria_inc", 
                               TRUE ~ NA_character_),
           asis = case_when((asiste_ci==1 & aedu_ci==0) | (asiste_ci==1 & edad_ci<=5) ~ "preescolar",
                            (asiste_ci==1 & (aedu_ci>=0  & aedu_ci<  6) & !is.na(asiste_ci)) & edad_ci >=6 ~ "primaria",
                            ((aedu_ci>=6  & aedu_ci<12) & asiste_ci == 1 & !is.na(asiste_ci)) & edad_ci>=6 ~ "secundaria", 
                            (aedu_ci>=12 & asiste_ci == 1 & asiste_ci == 1 & !is.na(asiste_ci)) & edad_ci>=6 ~ "terciaria",
                            asiste_ci==0 ~"no asiste",
                            is.na(asiste_ci) ~NA_character_),
           asis_neta = case_when((asiste_ci==1 & aedu_ci==0) | (asiste_ci==1 & edad_ci<=5) & age_edu == "preescolar" ~ "preescolar",
                                 (asiste_ci==1 & (aedu_ci>=0  & aedu_ci<  6) & !is.na(asiste_ci)) & edad_ci >=6  & age_edu == "primaria" ~ "primaria",
                                 ((aedu_ci>=6  & aedu_ci<12) & asiste_ci == 1 & !is.na(asiste_ci)) & edad_ci>=6 & age_edu == "secundaria"  ~ "secundaria", 
                                 (aedu_ci>=12 & asiste_ci == 1 & asiste_ci == 1 & !is.na(asiste_ci)) & edad_ci>=6 & age_edu == "terciaria" ~ "terciaria",
                                 asiste_ci==0 ~"no asiste",
                                 is.na(asiste_ci) ~NA_character_),
           grupo_etario = case_when(edad_ci>=4 & edad_ci<=5 ~ "age_4_5", 
                                    edad_ci >=6 & edad_ci<=11 ~ "age_6_11", 
                                    edad_ci >= 12 & edad_ci<=14 ~ "age_12_14", 
                                    edad_ci >=15 & edad_ci <=17 ~ "age_15_17", 
                                    edad_ci >=18 & edad_ci <=23 ~"age_18_23", 
                                    edad_ci >=25 ~"25_mas"), 
           anos_edu = case_when(aedu_ci==0 & (!is.na(aedu_ci) | !is.na(edad_ci)) & edad_ci >=25 ~ "anos_0",
                                aedu_ci>=1 & aedu_ci <=5 & (!is.na(aedu_ci) | !is.na(edad_ci)) & edad_ci >=25 ~ "anos_1_5", 
                                aedu_ci>=6 & aedu_ci <=6 & (!is.na(aedu_ci) | !is.na(edad_ci)) & edad_ci >=25 ~ "anos_6", 
                                aedu_ci>=7 & aedu_ci <=11 & (!is.na(aedu_ci) | !is.na(edad_ci)) & edad_ci >=25 ~ "anos_7_11", 
                                aedu_ci>=12 & aedu_ci <=12 & (!is.na(aedu_ci) | !is.na(edad_ci)) & edad_ci >=25 ~ "anos_12",
                                aedu_ci>=13 & (!is.na(aedu_ci) | !is.na(edad_ci)) & edad_ci >=25 ~ "anos_13_mas"),
           age_15_24_edu = ifelse(edad_ci>=15 & edad_ci<=24 & !is.na(asiste_ci), 1, 0),
           age_15_29_edu = ifelse(edad_ci>=15 & edad_ci<=29 & !is.na(asiste_ci), 1, 0),
           age_18_24_edu = ifelse(edad_ci>=18 & edad_ci<=24 & !is.na(asiste_ci), 1, 0)) %>% 
    select(age_25_mas, age_edu, asis, asis_neta, grupo_etario, age_15_24_edu, age_15_29_edu, age_18_24_edu, 
           anos_edu, asiste_ci,  region_BID_c, pais_c, geolev1, estrato_ci, zona_c, relacion_ci, idh_ch, factor_ch, factor_ci, 
           idp_ci) 
}

# 2. Encuestas

if (tipo == "encuestas") {
  
data_edu <- data_filt %>% 
  mutate(age_25_mas = ifelse(edad_ci>=25, 1, 0),
         #2. Ninis
         nini = ifelse(asiste_ci==0 & condocup_ci==3,1,0),
         #3. Edad teórica y asistencia
         #3.1 Primaria por grupo de países
         age_prim_c = case_when((pais_c=="COL"|pais_c=="BRA") & (edad_ci>=6&edad_ci<=10) ~ 1,
                                (pais_c=="COL"|pais_c=="BRA") ~ 0,
                                (pais_c=="BRB") & (edad_ci>=5&edad_ci<=10) ~ 1,
                                (pais_c=="BRB") ~ 0,
                                (pais_c=="TTO") & (edad_ci>=6&edad_ci<=12) ~ 1,
                                (pais_c=="TTO") ~ 0,
                                (edad_ci>=6&edad_ci<=10) ~ 1,
                                (edad_ci<6&edad_ci>10) ~ 0,
                                TRUE ~ NA),
         asis_net_prim_c = case_when((pais_c=="COL"|pais_c=="BRA") & (aedu_ci>=0 & aedu_ci<5) & (asiste_ci==1 & age_prim_c==1)~ 1,
                                     (pais_c=="COL"|pais_c=="BRA") & age_prim_c==1 & !(aedu_ci>=0 & aedu_ci<5 & asiste_ci==1)~ 0,
                                     (pais_c=="BRB") & (aedu_ci>=0 & aedu_ci<6) & (asiste_ci==1 & age_prim_c==1)~ 1,
                                     (pais_c=="BRB") & age_prim_c==1 & !(aedu_ci>=0 & aedu_ci<6 & asiste_ci==1)~ 0,
                                     (pais_c=="TTO") & (aedu_ci>=0 & aedu_ci<7) & (asiste_ci==1 & age_prim_c==1)~ 1,
                                     (pais_c=="TTO") & age_prim_c==1 & !(aedu_ci>=0 & aedu_ci<7 & asiste_ci==1)~ 0,
                                     (aedu_ci>=0 & aedu_ci<6)   & asiste_ci==1 & age_prim_c==1 ~ 1,
                                     age_prim_c==1 & !((aedu_ci>=0 & aedu_ci<6)   & asiste_ci==1)~ 0,
                                     TRUE ~ NA),
         asis_prim_c = case_when((pais_c=="COL"|pais_c=="BRA") & (aedu_ci>=0 & aedu_ci<5) & (asiste_ci==1 & edad_ci>=6)~ 1,
                                     (pais_c=="COL"|pais_c=="BRA") & edad_ci>=6 & is.na(asis_net_prim_c)~ 0,
                                     (pais_c=="BRB") & (aedu_ci>=0 & aedu_ci<6) & (asiste_ci==1 & edad_ci>=6)~ 1,
                                     (pais_c=="BRB") & edad_ci>=6 & is.na(asis_net_prim_c)~ 0,
                                     (pais_c=="TTO") & (aedu_ci>=0 & aedu_ci<7) & (asiste_ci==1 & edad_ci>=6)~ 1,
                                     (pais_c=="TTO") & edad_ci>=6 & is.na(asis_net_prim_c)~ 0,
                                     (aedu_ci>=0 & aedu_ci<6)   & asiste_ci==1 & edad_ci>=6 ~ 1,
                                      edad_ci>=6 & is.na(asis_net_prim_c)~ 0,
                                     TRUE ~ NA),
         #3.1.2 Sobreedad
         age_prim_sobre = case_when((pais_c=="BRB") &(asiste_ci==1 & aedu_ci==0 & edad_ci>=7)~ 1,
                                    (pais_c=="BRB") &(asiste_ci==1 & aedu_ci==1 & edad_ci>=8)~ 1,
                                    (pais_c=="BRB") &(asiste_ci==1 & aedu_ci==2 & edad_ci>=9)~ 1,
                                    (pais_c=="BRB") &(asiste_ci==1 & aedu_ci==3 & edad_ci>=10)~ 1,
                                    (pais_c=="BRB") &(asiste_ci==1 & aedu_ci==4 & edad_ci>=11)~ 1,
                                    (pais_c=="BRB") &(asiste_ci==1 & aedu_ci==5 & edad_ci>=12)~ 1,
                                    (pais_c=="BRB") &edad_ci>=5~ 0,
                                    (pais_c=="BRB")~ NA,
                                    (pais_c=="COL"|pais_c=="BRA") & (asiste_ci==1 & aedu_ci==0 & edad_ci>=8 & asispre_ci!= 1)~ 1,
                                    (pais_c=="COL"|pais_c=="BRA") & !(asiste_ci==1 & aedu_ci==0 & edad_ci>=8 & asispre_ci!= 1)~ 0,
                                    (pais_c=="COL"|pais_c=="BRA") & (asiste_ci==1 & aedu_ci==1 & edad_ci>=9)~ 1,
                                    (pais_c=="COL"|pais_c=="BRA") & (asiste_ci==1 & aedu_ci==2 & edad_ci>=10)~ 1,
                                    (pais_c=="COL"|pais_c=="BRA") & (asiste_ci==1 & aedu_ci==3 & edad_ci>=11)~ 1,
                                    (pais_c=="COL"|pais_c=="BRA") & (asiste_ci==1 & aedu_ci==4 & edad_ci>=12)~ 1,
                                    (pais_c=="TTO") & (asiste_ci==1 & aedu_ci==0 & edad_ci>=8)~ 1,
                                    (pais_c=="TTO") & !(asiste_ci==1 & aedu_ci==0 & edad_ci>=8)~ 0,
                                    (pais_c=="TTO") & (asiste_ci==1 & aedu_ci==1 & edad_ci>=9)~ 1,
                                    (pais_c=="TTO") & (asiste_ci==1 & aedu_ci==2 & edad_ci>=10)~ 1,
                                    (pais_c=="TTO") & (asiste_ci==1 & aedu_ci==3 & edad_ci>=11)~ 1,
                                    (pais_c=="TTO") & (asiste_ci==1 & aedu_ci==4 & edad_ci>=12)~ 1,                                 
                                    (pais_c=="TTO") & (asiste_ci==1 & aedu_ci==5 & edad_ci>=13)~ 1,
                                    (pais_c=="TTO") & (asiste_ci==1 & aedu_ci==6 & edad_ci>=14)~ 1,
                                    (pais_c=="TTO") & edad_ci<6 | is.na(aedu_ci)~ NA,
                                    (asiste_ci==1 & aedu_ci==0 & edad_ci>=8 & asispre_ci!= 1)~ 1,
                                    !(asiste_ci==1 & aedu_ci==0 & edad_ci>=8 & asispre_ci!= 1)~ 0,
                                    (asiste_ci==1 & aedu_ci==1 & edad_ci>=9)~ 1,
                                    (asiste_ci==1 & aedu_ci==2 & edad_ci>=10)~ 1,
                                    (asiste_ci==1 & aedu_ci==3 & edad_ci>=11)~ 1,
                                    (asiste_ci==1 & aedu_ci==4 & edad_ci>=12)~ 1,
                                    (asiste_ci==1 & aedu_ci==5 & edad_ci>=13)~ 1,
                                    edad_ci<6 | is.na(aedu_ci)~ NA,
                                 TRUE ~ NA),
         #3.1.3 Terminación
         age_term_p_c = case_when((pais_c=="COL"|pais_c=="BRA"|pais_c=="BRB")&(edad_ci>=13&edad_ci<=15)~ 1,
                                  (pais_c=="COL"|pais_c=="BRA"|pais_c=="BRB")&!(edad_ci>=13&edad_ci<=15)~ 0,
                                  (pais_c=="COL"|pais_c=="BRA"|pais_c=="BRB") & is.na(edupc_ci)~NA,
                                  pais_c=="TTO" & (edad_ci>=15&edad_ci<=17)~ 1,
                                  pais_c=="TTO" & !(edad_ci>=15&edad_ci<=17)~ 0,
                                  pais_c=="TTO" &is.na(edupc_ci)~NA,
                                  (edad_ci>=14&edad_ci<=16)~ 1,
                                  !(edad_ci>=14&edad_ci<=16)~ 0,
                                  is.na(edupc_ci)~NA
         ),
         #3.2 Secundaria por grupo de pasises
         #3.2.1 Edad teórica y asistencia
         age_seco_c = case_when((pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN") & (edad_ci>=12&edad_ci<=16) ~ 1,
                                (pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN") & !(edad_ci>=12&edad_ci<=16) ~ 0,
                                (pais_c=="HTI"|pais_c=="SUR") & (edad_ci>=12&edad_ci<=18) ~ 1,
                                (pais_c=="HTI"|pais_c=="SUR")& !(edad_ci>=12&edad_ci<=18) ~ 0,
                                (pais_c=="BRB") & (edad_ci>=11&edad_ci<=15) ~ 1,
                                (pais_c=="BRB")& !(edad_ci>=11&edad_ci<=15) ~ 0,
                                (pais_c=="COL") & (edad_ci>=11&edad_ci<=16) ~ 1,
                                (pais_c=="COL") & !(edad_ci>=11&edad_ci<=16) ~ 0,
                                (pais_c=="BRA") & (edad_ci>=11&edad_ci<=17) ~ 1,
                                (pais_c=="BRA")& !(edad_ci>=11&edad_ci<=17) ~ 0,                              
                                (pais_c=="TTO") & (edad_ci>=13&edad_ci<=18) ~ 1,
                                (pais_c=="TTO") & !(edad_ci>=13&edad_ci<=18) ~ 0,                                
                                (edad_ci<12&edad_ci>17) ~ 1,
                                !(edad_ci<12&edad_ci>17) ~ 0,
                                TRUE ~ NA),
         asis_net_seco_c = case_when((pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN") & (aedu_ci>=6 & aedu_ci<11) & asiste_ci==1 & age_seco_c==1~ 1,
                                     (pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN") & age_seco_c==1 & !((aedu_ci>=6 & aedu_ci<11) & asiste_ci==1)~ 0,
                                     (pais_c=="HTI"|pais_c=="SUR") & (aedu_ci>=6 & aedu_ci<13) & age_seco_c==1  & asiste_ci==1 ~ 1,
                                     (pais_c=="HTI"|pais_c=="SUR") & age_seco_c==1  & !((aedu_ci>=6 & aedu_ci<13) & asiste_ci==1) ~ 0,
                                     (pais_c=="BRB") & (aedu_ci>=6 & aedu_ci<11) & age_seco_c==1  & asiste_ci==1 ~ 1,
                                     (pais_c=="BRB") & age_seco_c==1 & !((aedu_ci>=6 & aedu_ci<11)   & asiste_ci==1) ~ 0,
                                     (pais_c=="COL") & (aedu_ci>=5 & aedu_ci<11) & age_seco_c==1  & asiste_ci==1 ~ 1,
                                     (pais_c=="COL") & age_seco_c==1 & !((aedu_ci>=5 & aedu_ci<11)   & asiste_ci==1) ~ 0,
                                     (pais_c=="BRA") & (aedu_ci>=5 & aedu_ci<12) & age_seco_c==1  & asiste_ci==1 ~ 1,
                                     (pais_c=="BRA") & age_seco_c==1 & !((aedu_ci>=5 & aedu_ci<12)   & asiste_ci==1) ~ 0,
                                     (pais_c=="TTO") & (aedu_ci>=7 & aedu_ci<12) & age_seco_c==1  & asiste_ci==1 ~ 1,
                                     (pais_c=="TTO") & age_seco_c==1 & !((aedu_ci>=7 & aedu_ci<12)   & asiste_ci==1) ~ 0,
                                     (aedu_ci>=6 & aedu_ci<12)   & asiste_ci==1 & age_seco_c==1 ~ 1,
                                     !((aedu_ci>=6 & aedu_ci<12)   & asiste_ci==1) & age_seco_c==1 ~ 0,
                                     TRUE ~ NA),         
         asis_seco_c = case_when((pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN") &  (aedu_ci>=6 & aedu_ci<11) & asiste_ci==1  & edad_ci>=6~ 1,
                                 (pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN" )& edad_ci>=6 &  !((aedu_ci>=6 & aedu_ci<11) & asiste_ci==1)  ~ 0,
                                 (pais_c=="HTI"|pais_c=="SUR") & (aedu_ci>=6 & aedu_ci<13) & edad_ci>=6  & asiste_ci==1 ~ 1,
                                 (pais_c=="HTI"|pais_c=="SUR") & edad_ci>=6 & !((aedu_ci>=6 & aedu_ci<13) & asiste_ci==1) ~ 0,
                                 (pais_c=="BRB") & (aedu_ci>=6 & aedu_ci<11) & edad_ci>=5  & asiste_ci==1 ~ 1,
                                 (pais_c=="BRB") & edad_ci>=5 & !((aedu_ci>=6 & aedu_ci<11)   & asiste_ci==1) ~ 0,
                                 (pais_c=="COL") & (aedu_ci>=5 & aedu_ci<11) & edad_ci>=6  & asiste_ci==1 ~ 1,
                                 (pais_c=="COL") & edad_ci>=6 & !((aedu_ci>=5 & aedu_ci<11)   & asiste_ci==1) ~ 0,                                 
                                 (pais_c=="BRA") & (aedu_ci>=5 & aedu_ci<12) & edad_ci>=6  & asiste_ci==1 ~ 1,
                                 (pais_c=="BRA") & edad_ci>=6 & !((aedu_ci>=5 & aedu_ci<12)   & asiste_ci==1) ~ 0,                                 
                                 (pais_c=="TTO") & (aedu_ci>=7 & aedu_ci<12) & edad_ci>=6  & asiste_ci==1 ~ 1,
                                 (pais_c=="TTO") & edad_ci>=6 & !((aedu_ci>=7 & aedu_ci<12)   & asiste_ci==1) ~ 0,
                                 (aedu_ci>=6 & aedu_ci<11)  & edad_ci>=6 & asiste_ci==1 ~ 1,
                                 !((aedu_ci>=6 & aedu_ci<11)  & asiste_ci==1)  & edad_ci>=6 ~ 1,
                                 TRUE ~ NA), 
         #3.2.1 Terminación
         age_term_s_c = case_when((pais_c=="COL"|pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN")&(edad_ci>=19&edad_ci<=21)~ 1,
                                  (pais_c=="COL"|pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN")&!(edad_ci>=19&edad_ci<=21)~ 0,
                                  (pais_c=="HTI"|pais_c=="SUR"|pais_c=="TTO")&(edad_ci>=21&edad_ci<=23) ~ 1,
                                  (pais_c=="HTI"|pais_c=="SUR"|pais_c=="TTO") &!(edad_ci>=21&edad_ci<=23) ~ 0,
                                  (pais_c=="BRB") &(edad_ci>=20&edad_ci<=22)~ 1,
                                  (pais_c=="BRB") & !(edad_ci>=20&edad_ci<=22) ~ 0,                                  
                                  (edad_ci>=20&edad_ci<=22)~ 1,
                                  !(edad_ci>=20&edad_ci<=22)~ 0,
                                  TRUE ~NA),
         #3.3 terciaria por grupo de pasises
         #3.3.1 Edad teórica y asistencia
         age_tert_c = case_when((pais_c=="COL"|pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN") & (edad_ci>=17&edad_ci<=23) ~ 1,
                                (pais_c=="COL"|pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN") & !(edad_ci>=17&edad_ci<=23) ~ 0,
                                (pais_c=="HTI"|pais_c=="SUR"|pais_c=="TTO")&(edad_ci>=19&edad_ci<=23) ~ 1,
                                (pais_c=="HTI"|pais_c=="SUR"|pais_c=="TTO")&!(edad_ci>=19&edad_ci<=23) ~ 0,
                                (pais_c=="BRB") &(edad_ci>=16&edad_ci<=23)~ 1,
                                (pais_c=="BRB") &!(edad_ci>=16&edad_ci<=23)~ 0,
                                (edad_ci>=18&edad_ci<=23)~ 1,
                                !(edad_ci>=18&edad_ci<=23)~ 0,
                                TRUE ~NA),
         
         
         asis_net_tert_c = case_when((pais_c=="COL"|pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN") & aedu_ci>11 & asiste_ci==1 & age_tert_c==1 ~ 1,
                                (pais_c=="COL"|pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN") & age_tert_c==1 & !(aedu_ci>11 & asiste_ci==1)  ~ 0,
                                (pais_c=="HTI"|pais_c=="SUR"|pais_c=="TTO") & aedu_ci>13 & asiste_ci==1 & age_tert_c==1 ~ 1,
                                (pais_c=="HTI"|pais_c=="SUR"|pais_c=="TTO") & age_tert_c==1 & !(aedu_ci>13 & asiste_ci==1) ~ 0,
                                (pais_c=="BRB") & aedu_ci>11 & asiste_ci==1 & age_tert_c==1~ 1,
                                (pais_c=="BRB") & age_tert_c==1 & !(aedu_ci>11 & asiste_ci==1) ~ 0,
                                aedu_ci>12 & asiste_ci==1 & age_tert_c==1 ~ 1,
                                age_tert_c==1 & !(aedu_ci>12 & asiste_ci==1) ~ 1,
                                TRUE ~NA),
         
         asis_tert_c = case_when((pais_c=="COL"|pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN") & aedu_ci>11 & asiste_ci==1 & edad_ci>=6 ~ 1,
                                 (pais_c=="COL"|pais_c=="CRI"|pais_c=="GTM"|pais_c=="GUY"|pais_c=="JAM"|pais_c=="NIC"|pais_c=="PER"|pais_c=="VEN") & edad_ci>=6 & !(aedu_ci>11 & asiste_ci==1)  ~ 0,
                                 (pais_c=="HTI"|pais_c=="SUR"|pais_c=="TTO") & aedu_ci>13 & asiste_ci==1 & edad_ci>=6~ 1,
                                 (pais_c=="HTI"|pais_c=="SUR"|pais_c=="TTO") & edad_ci>=6 & !(aedu_ci>13 & asiste_ci==1) ~ 0,
                                 (pais_c=="BRB") & aedu_ci>11 & asiste_ci==1 & edad_ci>=5~ 1,
                                 (pais_c=="BRB") & edad_ci>=5 & !(aedu_ci>11 & asiste_ci==1) ~ 0,
                                 TRUE ~NA),
        
         # 4 leavers
         leavers = ifelse((edupi_ci==1 | edupc_ci==1 | edus1i_ci==1 | edus1c_ci==1) & (asiste_ci == 0),1,0),
         tprimaria = ifelse((edupc_ci ==1 | edusi_ci==1 | edusc_ci==1 | eduui_ci==1 | eduuc_ci==1),1,0),
         tsecundaria  = ifelse((edusc_ci ==1 | eduui_ci==1 | eduuc_ci==1),1,0),
         tsuperior = ifelse((eduuc_ci ==1),1,0),
         t_cond_primaria   = ifelse((tprimaria==1   & age_term_p_c==1),1,0),
         t_cond_secundaria = ifelse((tsecundaria==1 & age_term_s_c==1),1,0),
         # 5 Desagregación por niveles
         nivel_ed_ = case_when(eduno_ci==1 | edupi_ci==1~ 0,
                               edupc_ci==1 | edusi_ci==1~ 1,
                               edusc_ci==1 | eduui_ci==1~ 2,
                               eduuc_ci==1~ 3),
         nivel_ed_1 = case_when(eduno_ci==1~ 0,
                                edupi_ci==1~ 1,
                                edupc_ci==1~ 2,
                                edusi_ci==1~ 3,
                                edusc_ci==1~ 4,
                                eduui_ci==1~ 5,
                                eduuc_ci==1~ 6,
                                TRUE ~NA)) %>% 
  select(age_25_mas:nivel_ed_1,  region_BID_c, pais_c, ine01, estrato_ci, zona_c, relacion_ci, idh_ch, factor_ch, factor_ci, 
         idp_ci) 
}